name: leetcode_api_dart
description: Leetcode API for Dart
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  dotenv: ^4.1.0
  test: ^1.24.6
